### ISSUE TITLE
How do I use this class to get md5 of a binary file content?

### ISSUE THREAD

**Issue by jasonmnemonic** [oalexandrefreire/MD5#2]
Just seen your examples, it works on strings but can I use this class to work on a file. So I load the file and get the md5 of the file.

Thanks.

**Comment by oalexandrefreire** [comment]
Hello @jasonmnemonic . Thanks so much for using the MD5 library. It's really not possible to get it from a binary file, but I found it interesting and I'm going to implement this feature today.

**Comment by oalexandrefreire** [comment]
The feature already available in version 2.0.4. Upgrade to get access!
[MD5](https://www.nuget.org/packages/MD5)
[README updated](https://github.com/oalexandrefreire/MD5#readme)
